-- jsonb sorts object keys; these objects are shown back in the order they were written, so they move to json.
-- Generated by drizzle-kit, then made explicit: the jsonb default is dropped before the type change, the change casts
-- with USING, and the json default is set again.
ALTER TABLE "custom_tools" ALTER COLUMN "parameters" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "custom_tools" ALTER COLUMN "parameters" SET DATA TYPE json USING "parameters"::json;--> statement-breakpoint
ALTER TABLE "custom_tools" ALTER COLUMN "parameters" SET DEFAULT '{}'::json;--> statement-breakpoint
ALTER TABLE "custom_tools" ALTER COLUMN "headers" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "custom_tools" ALTER COLUMN "headers" SET DATA TYPE json USING "headers"::json;--> statement-breakpoint
ALTER TABLE "custom_tools" ALTER COLUMN "headers" SET DEFAULT '{}'::json;--> statement-breakpoint
ALTER TABLE "contacts" ALTER COLUMN "custom_fields" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "contacts" ALTER COLUMN "custom_fields" SET DATA TYPE json USING "custom_fields"::json;--> statement-breakpoint
ALTER TABLE "contacts" ALTER COLUMN "custom_fields" SET DEFAULT '{}'::json;
