"use client";

import { LoaderCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { toast } from "sonner";
import { FormMessage } from "@/components/form-message";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Field, FieldDescription, FieldError, FieldLabel, FieldLegend, FieldSet } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { ActionFailure } from "@/lib/action-result";
import { AGENT_NAME_MAX } from "@/lib/agent-input";
import type { Sector } from "@/lib/enums";
import { createAgentAction } from "../../actions";
import { DraftGenerator } from "../../_components/draft-generator";
import { InstructionFields } from "../../_components/instruction-fields";
import { instructionValues, type InstructionValues } from "../../_lib/instructions";
import type { NewAgentRequest } from "../../_lib/requests";

export type TemplateOption = { sector: Sector; label: string; name: string; description: string };

type Choice = "sector" | "other" | "blank" | "draft";

type NewAgentFormProps = {
  /** Template of the business's sector (Ajustes › Negocio). */
  businessTemplate: TemplateOption;
  otherTemplates: TemplateOption[];
  businessWebsite: string | null;
  /** There is an OpenRouter key: «Generar borrador con IA» works ([ARR-14]). */
  aiConfigured: boolean;
};

/**
 * «Nuevo agente» ([AGE-02], [AGE-05]): the template of the business sector, another sector's, blank, or a draft
 * generated by the AI that the person reviews before creating. Creating opens the editor.
 */
export function NewAgentForm({ businessTemplate, otherTemplates, businessWebsite, aiConfigured }: NewAgentFormProps) {
  const router = useRouter();
  const [choice, setChoice] = useState<Choice>("sector");
  const [otherSector, setOtherSector] = useState<Sector>(otherTemplates[0]?.sector ?? businessTemplate.sector);
  const [name, setName] = useState(businessTemplate.name);
  const [nameTyped, setNameTyped] = useState(false);
  const [draft, setDraft] = useState<InstructionValues | null>(null);
  const [draftTone, setDraftTone] = useState<string | null>(null);
  const [failure, setFailure] = useState<ActionFailure | null>(null);
  const [pending, startTransition] = useTransition();
  const other = otherTemplates.find((template) => template.sector === otherSector) ?? businessTemplate;

  /** The name follows the chosen template until the person types their own. */
  function suggestName(nextChoice: Choice, nextOther: TemplateOption) {
    if (nameTyped) return;
    setName(nextChoice === "blank" ? "" : nextChoice === "other" ? nextOther.name : businessTemplate.name);
  }

  function request(): NewAgentRequest | null {
    switch (choice) {
      case "sector":
        return { source: "template", sector: businessTemplate.sector, name };
      case "other":
        return { source: "template", sector: otherSector, name };
      case "blank":
        return { source: "blank", name };
      case "draft":
        return draft ? { source: "draft", sector: businessTemplate.sector, name, instructions: draft, ...(draftTone ? { tone: draftTone } : {}) } : null;
    }
  }

  function submit() {
    const input = request();
    if (!input) {
      setFailure({ ok: false, error: "Genera primero el borrador o elige otra forma de empezar." });
      return;
    }
    startTransition(async () => {
      const result = await createAgentAction(input);
      if (!result.ok || !result.data) {
        setFailure(result.ok ? { ok: false, error: "No se ha podido crear el agente." } : result);
        return;
      }
      toast.success(result.message ?? "Agente creado.");
      router.push(`/agentes/${result.data.id}`);
    });
  }

  const errorsFor = (path: string) => {
    const entries = Object.entries(failure?.fieldErrors ?? {}).filter(([key]) => key === path || key.startsWith(`${path}.`));
    return entries.length > 0 ? entries.flatMap(([, messages]) => messages) : undefined;
  };
  const nameErrors = errorsFor("name");

  return (
    <form
      noValidate
      onSubmit={(event) => {
        event.preventDefault();
        submit();
      }}
      className="grid max-w-2xl gap-8"
    >
      <FieldSet>
        <FieldLegend variant="label">¿Cómo quieres empezar?</FieldLegend>
        <RadioGroup
          value={choice}
          onValueChange={(value) => {
            const next = (["sector", "other", "blank", "draft"] as const).find((option) => option === value);
            if (!next) return;
            setChoice(next);
            setFailure(null);
            suggestName(next, other);
          }}
          className="grid gap-3"
        >
          <ChoiceCard value="sector" title={`Plantilla de ${businessTemplate.label}`} badge="Recomendada">
            {businessTemplate.description}
          </ChoiceCard>
          <ChoiceCard value="other" title="Plantilla de otro sector">
            Para un agente que atiende algo distinto de lo habitual en tu sector.
          </ChoiceCard>
          <ChoiceCard value="blank" title="En blanco">
            Sin instrucciones: las escribes tú desde cero.
          </ChoiceCard>
          <ChoiceCard value="draft" title="Generar borrador con IA">
            A partir de la web de tu negocio o de una descripción. Lo revisas antes de crear el agente.
          </ChoiceCard>
        </RadioGroup>
        {choice === "other" ? (
          <div className="grid gap-2 rounded-lg border p-3">
            <label htmlFor="new-agent-other-sector" className="text-sm font-medium">
              Sector
            </label>
            <Select
              value={otherSector}
              onValueChange={(value) => {
                const template = otherTemplates.find((option) => option.sector === value);
                if (!template) return;
                setOtherSector(template.sector);
                suggestName("other", template);
              }}
            >
              <SelectTrigger id="new-agent-other-sector" className="w-full sm:w-72">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {otherTemplates.map((template) => (
                  <SelectItem key={template.sector} value={template.sector}>
                    {template.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-sm text-muted-foreground">{other.description}</p>
          </div>
        ) : null}
      </FieldSet>

      {choice === "draft" ? (
        <section aria-labelledby="new-agent-draft-title" className="grid gap-4 rounded-xl border p-4">
          <h2 id="new-agent-draft-title" className="text-base font-semibold">
            Borrador de las instrucciones
          </h2>
          <DraftGenerator
            defaultUrl={businessWebsite}
            aiConfigured={aiConfigured}
            idPrefix="new-agent-draft"
            onDraft={(generated) => {
              setDraft(instructionValues(generated.instructions));
              setDraftTone(generated.tone);
              if (!nameTyped) setName(generated.name);
              setFailure(null);
            }}
          />
          {draft ? (
            <div className="grid gap-3 border-t pt-4">
              <p className="text-sm text-muted-foreground">
                Revísalo y cámbialo lo que quieras. El nombre y el tono también vienen del borrador; el traspaso y sus mensajes, de la plantilla
                de tu sector.
              </p>
              <InstructionFields
                idPrefix="new-agent-instructions"
                values={draft}
                onChange={(key, value) => setDraft({ ...draft, [key]: value })}
                errorsFor={errorsFor}
              />
            </div>
          ) : null}
        </section>
      ) : null}

      <Field data-invalid={nameErrors ? true : undefined}>
        <FieldLabel htmlFor="new-agent-name">Nombre del agente</FieldLabel>
        <Input
          id="new-agent-name"
          value={name}
          maxLength={AGENT_NAME_MAX}
          placeholder="Recepción"
          onChange={(event) => {
            setName(event.target.value);
            setNameTyped(true);
          }}
          aria-invalid={nameErrors ? true : undefined}
          aria-describedby="new-agent-name-help"
        />
        <FieldDescription id="new-agent-name-help">Podrás cambiarlo, igual que todo lo demás, en el editor.</FieldDescription>
        <FieldError errors={nameErrors?.map((message) => ({ message }))} />
      </Field>

      <div className="flex flex-wrap items-center gap-4">
        <Button type="submit" disabled={pending} aria-busy={pending}>
          {pending ? <LoaderCircle aria-hidden className="animate-spin motion-reduce:animate-none" /> : null}
          {pending ? "Creando…" : "Crear agente"}
        </Button>
        {failure && !nameErrors ? <FormMessage result={failure} /> : null}
      </div>
    </form>
  );
}

function ChoiceCard({ value, title, badge, children }: { value: Choice; title: string; badge?: string; children: string }) {
  const id = `new-agent-${value}`;
  return (
    <div className="flex items-start gap-3 rounded-lg border p-3 has-data-[state=checked]:border-primary has-data-[state=checked]:bg-primary-soft">
      <RadioGroupItem id={id} value={value} className="mt-0.5" aria-describedby={`${id}-help`} />
      <div className="grid gap-1">
        <label htmlFor={id} className="flex flex-wrap items-center gap-2 text-sm font-medium">
          {title}
          {badge ? (
            <Badge variant="outline" className="h-[22px]">
              {badge}
            </Badge>
          ) : null}
        </label>
        <p id={`${id}-help`} className="text-sm text-muted-foreground">
          {children}
        </p>
      </div>
    </div>
  );
}
